### ISSUE TITLE
Not storing sensitive stuff in localStorage

### ISSUE THREAD

**Issue by sedubois** [jlengstorf/gatsby-demo-simple-auth#1]
Thanks @jlengstorf! I've been really wondering how to migrate our current web app into our marketing-only Gatsby site, this is going be to a helpful start 🙂

It looks like in the demo you [store](https://github.com/jlengstorf/gatsby-demo-simple-auth/blob/526b368308320125b01427dbb5894b1d52ae4ad4/src/utils/auth.js#L22) private user info into `localStorage`, which [this article recommends against](https://www.rdegges.com/2018/please-stop-using-local-storage/) because of XSS (I made a similar observation in https://github.com/howtographql/howtographql/issues/550). Do you agree with that? 

Should this example instead use secure cookies as mentioned in the article? How do we do that as there's no dedicated web server in a static site, should we make use of e.g. the new Netlify functions? Thanks a lot

**Comment by jlengstorf** [comment]
Hey, @sedubois! Yeah, I wouldn't put user info in localStorage in production. A production app could stand up an API or use something like Netlify functions to load any custom data. It would be required for any kind of dynamic back-end anyways (since we can't pre-build any user-specific stuff during the Gatsby build process).

Does that make sense?

**Comment by sedubois** [comment]
@jlengstorf thanks, so if I understand right, the demo code in auth.js should be fixed to [authenticate](https://github.com/jlengstorf/gatsby-demo-simple-auth/blob/526b368308320125b01427dbb5894b1d52ae4ad4/src/utils/auth.js#L17), [store](https://github.com/jlengstorf/gatsby-demo-simple-auth/blob/526b368308320125b01427dbb5894b1d52ae4ad4/src/utils/auth.js#L10) and [retrieve](https://github.com/jlengstorf/gatsby-demo-simple-auth/blob/526b368308320125b01427dbb5894b1d52ae4ad4/src/utils/auth.js#L5) user data against a remote API or serverless system instead of the hard-coded creds + local storage (although I don't yet know how to do that).

IMHO if this demo keeps using localStorage, it should at least show a warning that such a pattern is unsuitable for production.

**Comment by jlengstorf** [comment]
Hey, @sedubois, this example is less about showing authentication, and more about showing Gatsby's ability to support dynamic content in client-only routes.

That being said, I'd recommend looking at something like [Auth0](https://auth0.com) or [Passport.js](http://www.passportjs.org/) to handle authentication in your apps. Rolling a custom auth system is hard and likely to have security holes, and Auth0/Passport are both battle tested and widely used.

I'll add a disclaimer to this repo to explain this, and I'll add it to my todo list to set up a demo app using one or both services (with a demo back-end) to show a more production-ready auth setup.

Thanks!
